name: Build & Publish content
on:
  push:
    branches:
    - main
  workflow_dispatch:
    
permissions:
  id-token: write
  contents: read

jobs:
  build_publish:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18.x]
    environment: prod
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
              az storage blob upload-batch --account-name jeebstorage -d '$web' -s ./output
              
      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
              az cdn endpoint purge --content-paths  "/*" --profile-name "jeeb-cdn" --name "jeeb-cdnep" --resource-group "jeeb-uk"

      - name: logout
        run: |
              az logout